stages:
  data_ingestion:
    cmd: python src/MoviesRecom/pipeline/stage_01_data_ingestion.py
    deps:
      - src/MoviesRecom/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/movie_dataset.zip
      - artifacts/data_ingestion/movie_dataset
