stages:
  data_ingestion:
    cmd: python src/MoviesRecom/pipeline/stage_01_data_ingestion.py
    deps:
      - src/MoviesRecom/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/movie_dataset.zip
      - artifacts/data_ingestion/movie_dataset

  data_validation:
    cmd: python src/MoviesRecom/pipeline/stage_02_data_validation.py
    deps:
      - src/MoviesRecom/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/movie_dataset
    outs:
      - artifacts/data_validation/status.txt
