artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_url: https://github.com/FraidoonOmarzai/data/raw/main/movie_dataset.zip
  local_data_file: artifacts/data_ingestion/movie_dataset.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/movie_dataset
  status: artifacts/data_validation/status.txt